# Generated by Django 4.1.2 on 2022-10-05 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Группа продуктов')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='meals',
            field=models.ManyToManyField(to='bot_db.meal'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bot_db.product_group'),
            preserve_default=False,
        ),
    ]
