# Generated by Django 4.1.2 on 2022-10-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_db', '0002_product_group_ingredient_meals_ingredient_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='meals',
        ),
        migrations.AddField(
            model_name='meal',
            name='ingredients',
            field=models.ManyToManyField(to='bot_db.ingredient'),
        ),
    ]
