# Generated by Django 4.1.2 on 2022-10-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_db', '0004_alter_ingredient_group_alter_meal_diet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='Telegram ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='Полное имя')),
                ('phonenumber', models.CharField(max_length=30, verbose_name='Номер телефона')),
            ],
        ),
    ]
