# Generated by Django 4.1.2 on 2022-10-06 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_db', '0005_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phonenumber',
            new_name='phone_number',
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('sent_free', models.IntegerField(verbose_name='Бесплатных отправлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_db.user')),
            ],
        ),
    ]
