# Generated by Django 4.1.2 on 2022-10-08 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_db', '0006_rename_phonenumber_user_phone_number_subscription'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_group',
            new_name='ProductGroup',
        ),
        migrations.RenameModel(
            old_name='Meal',
            new_name='Recipe',
        ),
        migrations.AddField(
            model_name='user',
            name='excluded_recipes',
            field=models.ManyToManyField(related_name='excluded', to='bot_db.recipe'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_recipes',
            field=models.ManyToManyField(related_name='favorites', to='bot_db.recipe'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot_db.user'),
        ),
    ]
