# Generated by Django 4.1.2 on 2022-10-09 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_db', '0008_recipe_description_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot_db.productgroup', verbose_name='Продуктовая группа'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Номер телефона'),
        ),
    ]
