# Generated by Django 4.1.2 on 2022-10-10 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_db', '0010_alter_user_excluded_recipes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='group',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='diet',
            field=models.CharField(max_length=50, verbose_name='Тип диеты'),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.DeleteModel(
            name='Diet',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='ProductGroup',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default='', verbose_name='Ингредиенты'),
            preserve_default=False,
        ),
    ]
