# Generated by Django 4.1.2 on 2022-10-10 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bot_db", "0011_remove_ingredient_group_alter_recipe_diet_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Diet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Тип диеты")),
            ],
        ),
        migrations.AlterField(
            model_name="recipe",
            name="diet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="bot_db.diet",
                verbose_name="Тип диеты",
            ),
        ),
    ]
