# Generated by Django 4.1.2 on 2022-10-10 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot_db", "0012_diet_alter_recipe_diet"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="Customer",
        ),
    ]
