# Generated by Django 4.1.2 on 2022-10-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_db", "0013_rename_user_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.CharField(
                default="", max_length=255, verbose_name="Изображение"
            ),
            preserve_default=False,
        ),
    ]
